# Generated by Django 5.1.2 on 2025-01-01 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_myaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='customer',
        ),
    ]
